#!/usr/bin/env Rscript
# USAGE: `Rscript locate.R <infile> ?<countrycode>`
# OUTPUT: ./located/{countrycode}/{countrycode}-latest-estimate.csv

# This script processes the .csv files generated by `fetch.R` and 
# replaces the `region` values with proper identifiers for geocoding.
# It will try to automatically guess the country from the first two letters
# of the filename; if the file is not stored with the country code first,
# then the country can be specified optionally after the <infile> parameter.

# imports
library(data.table); 'Imports successful'


# argument parsing
args <- commandArgs(trailingOnly=TRUE)

if (length(args) != 1 && length(args) != 2) { 
    stop(
        paste('',
        'Insufficient arguments provided.',
        'Please see USAGE:',
        '   `Rscript transform.R <infile> ?<countrycode>`',
        sep='\n')
    )
}

args.infile <- args[1]
if (length(args) == 2) {
    args.countrycode <- args[2]
} else {
    path <- strsplit(args[1], '/')[[1]]
    filename <- path[length(path)]
    args.countrycode <- paste(strsplit(filename, '')[[1]][1:2], collapse='')
}
'Arguments parsed successfully'

# read in data
infile <- fread(args.infile)
COUNTRIES <- c('US')
if (!(args.countrycode %in% COUNTRIES)) {
    stop(
        paste('',
        'Country not supported.',
        'Please see available countries:',
        paste(COUNTRIES, collapse=', '),
        sep='\n')
    )
}
'Data received successfully'


# transform data
for ( i in 1:nrow(infile) ) {
    row <- as.character(infile[i, 3])
    infile[i, 3] <- substr(row, start=3, stop=nchar(row))
}; 'Transformation complete'


# output data
setwd('./located/')
if (!dir.exists(args.countrycode)) dir.create(args.countrycode)
write.csv(
    infile,
    paste(
        args.countrycode, '/',
        args.countrycode, '-latest-estimate.csv',
        sep=''
    ),
    quote=FALSE
)
paste(
    'Process completed; output stored at ./located/', 
    args.countrycode, '/', 
    args.countrycode, '-latest-estimate.csv', 
    sep=''
)

'Exited with 0; operation successful'
