#!/usr/bin/env Rscript
# USAGE: `Rscript locate.R <infile> <outfile>`
# OUTPUT: <outfile>


# This script processes .csv files generated by `fetch.R` and adds the proper names of the 
# administrative regions to the data. The administrative region names are looked up by their 
# region code in:
# > https://github.com/GCGImdea/coronasurveys/blob/master/data/common-data/regions-tree-population-v2.csv


# imports
library(data.table); 'Imports successful'


# argument parsing
args <- commandArgs(trailingOnly=TRUE)

if (length(args) != 2) { 
    stop(
        paste('',
        'Insufficient arguments provided.',
        'Please see USAGE:',
        '   `Rscript locate.R <infile> <outfile>`',
        sep='\n')
    )
}

args.infile <- args[1]
args.outfile <- args[2]

'Arguments parsed successfully'


# read in data
infile <- fread(args.infile)
regions <- fread('https://raw.githubusercontent.com/GCGImdea/coronasurveys/master/data/common-data/regions-tree-population-v2.csv')

# map regions to data
map <- c()
for ( i in 1:nrow(regions) ) {
    map <- c(map, regions[regioncode == infile[i, 'regioncode']][['JHU_region']])
}

# process outfile
outfile <- data.table(
    p_cases = infile$p_cases,
    p_cases_error = infile$p_cases_error,
    p_fatalities = infile$p_fatalities,
    p_fatalities_error = infile$p_fatalities_error,
    p_recentcases = infile$p_recentcases,
    p_recentcases_error = infile$p_recentcases_error,
    p_cases_daily = infile$p_cases_daily,
    p_cases_daily_error = infile$p_cases_daily_error,
    p_stillsick = infile$p_stillsick,
    p_stillsick_error = infile$p_stillsick_error,
    region = map
)

'Data processing complete'


# write outfile
write.csv(outfile, args.outfile, quote=FALSE)
paste('Process completed; output stored at', args.outfile)

'Exited with 0; operation successful'
