"""
This script creates a map using CARTO's API.
It takes the products of the other data processing scripts and uses 
CARTO to transform them into a map. In order to access the CARTO API,
the user must have a CARTO account and a CARTO API key, which should be
stored at '../creds/creds.json'.

"""
from cartoframes.viz.widgets.default_widget import default_widget
import pandas as pd
from cartoframes.auth import set_default_credentials
from cartoframes.data.services import Geocoding
from cartoframes.viz import Map, Layer, size_continuous_style, color_continuous_style

set_default_credentials('../creds/creds.json')

located = pd.read_csv('located/ES/ES-geo.csv')
geocoded, metadata = Geocoding().geocode(located, 'region', 
                     country={'value': 'Spain'})

style_size = size_continuous_style('p_cases', size_range=[10, 75])

mapped = Map(
    Layer(
        geocoded, 
        style_size, 
        title='Estimated Cases (%)',
        default_widget=True
    )
)

mapped.publish('Autogenerated Test Map', None, if_exists='replace')
print('Map published!')
