#!/usr/bin/env Rscript
# USAGE: `Rscript map.R`
# OUTPUT: Plotly map

# This script processes all .csv files generated by `locate.R` and
# all .geojson mapping files to create the Plotly map displaying the relevant data.
# TODO: Currently, only US is supported

# imports
import json
from plotly import graph_objects as go
import pandas as pd


# get data
data = pd.read_csv('./located/US/US-latest-estimate.csv')
with open('./maps/us.geojson', 'r') as f:
    map = json.load(f)

# graph
fig = go.Figure(go.Choroplethmapbox(
    geojson=map,
    locations=data.region,
    z=data.p_infected,
    zmin=0, zmax=1,
    colorscale=[
        [0, '#adffc2'],
        [0.5, '#ff9382'],
        [1, '#c90061']
    ],
    marker_line_width=0,
    marker_opacity=0.75,
))
fig.update_layout(
    mapbox_style='open-street-map',
    mapbox_zoom=3,
    mapbox_center={'lat': 37.0902, 'lon': -95.7129},
)
fig.update_layout(
    margin={ 'r': 0, 't': 0, 'l': 0, 'b': 0 }
)
fig.show()
