#!/usr/bin/env Rscript
# USAGE: `Rscript transform.R <infile>`
# OUTPUT: Transformed <infile>


# This script processes the geo-tagged .csv files generated by `locate.R` and 
# replaces incorrect English names of Spanish autonomous communities with their respective Spanish 
# names. For example, "Andalusia" is transformed into "Andalucía".


# imports
library(data.table); 'Imports successful'


# argument parsing
args <- commandArgs(trailingOnly=TRUE)

if (length(args) != 1) { 
    stop(
        paste('',
        'Insufficient arguments provided.',
        'Please see USAGE:',
        '   `Rscript transform.R <infile>`',
        sep='\n')
    )
}

args.infile <- args[1]; 'Arguments parsed successfully'


# read in data
infile <- fread(args.infile)
regions_eng <- c('Andalusia', 'Aragon', 'Pais Vasco', 'C. Valenciana')
regions_es <- c('Andalucía', 'Aragón', 'País Vasco', 'Valencia')
'Data received successfully'


# transform data
count <- 1
for ( i in 1:nrow(infile) ) {
    if (infile[i, 12] %in% regions_eng) {
        infile[i, 12] <- regions_es[count]
        count <- count + 1
    }
}; 'Transformation complete'


# output data
write.csv(infile, args.infile, quote=FALSE)
paste('Process completed')

'Exited with 0; operation successful'
